window.WCAG_DATA = [
    {
        "principle": "Perceivable",
        "guideline": "Text Alternatives",
        "sc": "1.1.1 Non-Text Content",
        "scNumber": "1.1.1",
        "scName": "Non-Text Content",
        "level": "A",
        "description": "All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, except for the situations listed below.\n\nControls, Input\nIf non-text content is a control or accepts user input, then it has a name that describes its purpose. (Refer to Success Criterion 4.1.2 for additional requirements for controls and content that accepts user input.)\n\nTime-Based Media\nIf non-text content is time-based media, then text alternatives at least provide descriptive identification of the non-text content. (Refer to Guideline 1.2 for additional requirements for media.)\n\nTest\nIf non-text content is a test or exercise that would be invalid if presented in text, then text alternatives at least provide descriptive identification of the non-text content.\n\nSensory\nIf non-text content is primarily intended to create a specific sensory experience, then text alternatives at least provide descriptive identification of the non-text content.\n\nCAPTCHA\nIf the purpose of non-text content is to confirm that content is being accessed by a person rather than a computer, then text alternatives that identify and describe the purpose of the non-text content are provided, and alternative forms of CAPTCHA using output modes for different types of sensory perception are provided to accommodate different disabilities.\n\nDecoration, Formatting, Invisible\nIf non-text content is pure decoration, is used only for visual formatting, or is not presented to users, then it is implemented in a way that it can be ignored by assistive technology.",
        "shortDescription": "All non-text content that is presented to the user has a text alternative that serves the equivalent purpose, except for the situations listed below.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.1 Audio-only and Video-only (Prerecorded)",
        "scNumber": "1.2.1",
        "scName": "Audio-only and Video-only (Prerecorded)",
        "level": "A",
        "description": "For prerecorded audio-only and prerecorded video-only media, the following are true, except when the audio or video is a media alternative for text and is clearly labeled as such:\n\nPrerecorded Audio-only\nAn alternative for time-based media is provided that presents equivalent information for prerecorded audio-only content.\n\nPrerecorded Video-only\nEither an alternative for time-based media or an audio track is provided that presents equivalent information for prerecorded video-only content.",
        "shortDescription": "For prerecorded audio-only and prerecorded video-only media, the following are true, except when the audio or video is a media alternative for text and is clearly labeled as such:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.2 Captions (Prerecorded)",
        "scNumber": "1.2.2",
        "scName": "Captions (Prerecorded)",
        "level": "A",
        "description": "Captions are provided for all prerecorded audio content in synchronized media, except when the media is a media alternative for text and is clearly labeled as such.",
        "shortDescription": "Captions are provided for all prerecorded audio content in synchronized media, except when the media is a media alternative for text and is clearly labeled as such.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.3 Audio Description or Media Alternative (Prerecorded)",
        "scNumber": "1.2.3",
        "scName": "Audio Description or Media Alternative (Prerecorded)",
        "level": "A",
        "description": "An alternative for time-based media or audio description of the prerecorded video content is provided for synchronized media, except when the media is a media alternative for text and is clearly labeled as such.",
        "shortDescription": "An alternative for time-based media or audio description of the prerecorded video content is provided for synchronized media, except when the media is a media alternative for text and is clearly labeled as such.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.4 Captions (Live)",
        "scNumber": "1.2.4",
        "scName": "Captions (Live)",
        "level": "AA",
        "description": "Captions are provided for all live audio content in synchronized media.",
        "shortDescription": "Captions are provided for all live audio content in synchronized media.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.5 Audio Description (Prerecorded)",
        "scNumber": "1.2.5",
        "scName": "Audio Description (Prerecorded)",
        "level": "AA",
        "description": "Audio description is provided for all prerecorded video content in synchronized media.",
        "shortDescription": "Audio description is provided for all prerecorded video content in synchronized media.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.6 Sign Language (Prerecorded)",
        "scNumber": "1.2.6",
        "scName": "Sign Language (Prerecorded)",
        "level": "AAA",
        "description": "Sign language interpretation is provided for all prerecorded audio content in synchronized media.",
        "shortDescription": "Sign language interpretation is provided for all prerecorded audio content in synchronized media.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.7 Extended Audio Description (Prerecorded)",
        "scNumber": "1.2.7",
        "scName": "Extended Audio Description (Prerecorded)",
        "level": "AAA",
        "description": "Where pauses in foreground audio are insufficient to allow audio descriptions to convey the sense of the video, extended audio description is provided for all prerecorded video content in synchronized media.",
        "shortDescription": "Where pauses in foreground audio are insufficient to allow audio descriptions to convey the sense of the video, extended audio description is provided for all prerecorded video content in synchronized media.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.8 Media Alternative (Prerecorded)",
        "scNumber": "1.2.8",
        "scName": "Media Alternative (Prerecorded)",
        "level": "AAA",
        "description": "An alternative for time-based media is provided for all prerecorded synchronized media and for all prerecorded video-only media.",
        "shortDescription": "An alternative for time-based media is provided for all prerecorded synchronized media and for all prerecorded video-only media.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Time-based Media",
        "sc": "1.2.9 Audio-only (Live)",
        "scNumber": "1.2.9",
        "scName": "Audio-only (Live)",
        "level": "AAA",
        "description": "An alternative for time-based media that presents equivalent information for live audio-only content is provided.",
        "shortDescription": "An alternative for time-based media that presents equivalent information for live audio-only content is provided.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Adaptable",
        "sc": "1.3.1 Info and Relationships",
        "scNumber": "1.3.1",
        "scName": "Info and Relationships",
        "level": "A",
        "description": "Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.",
        "shortDescription": "Information, structure, and relationships conveyed through presentation can be programmatically determined or are available in text.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Adaptable",
        "sc": "1.3.2 Meaningful Sequence",
        "scNumber": "1.3.2",
        "scName": "Meaningful Sequence",
        "level": "A",
        "description": "When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined.",
        "shortDescription": "When the sequence in which content is presented affects its meaning, a correct reading sequence can be programmatically determined.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Adaptable",
        "sc": "1.3.3 Sensory Characteristics",
        "scNumber": "1.3.3",
        "scName": "Sensory Characteristics",
        "level": "A",
        "description": "Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components such as shape, color, size, visual location, orientation, or sound.\n\nNOTE\nFor requirements related to color, refer to Guideline 1.4.",
        "shortDescription": "Instructions provided for understanding and operating content do not rely solely on sensory characteristics of components such as shape, color, size, visual location, orientation, or sound.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Adaptable",
        "sc": "1.3.4 Orientation",
        "scNumber": "1.3.4",
        "scName": "Orientation",
        "level": "AA",
        "description": "Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.\n\nNOTE\nExamples where a particular display orientation may be essential are a bank check, a piano application, slides for a projector or television, or virtual reality content where binary display orientation is not applicable.",
        "shortDescription": "Content does not restrict its view and operation to a single display orientation, such as portrait or landscape, unless a specific display orientation is essential.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Adaptable",
        "sc": "1.3.5 Identify Input Purpose",
        "scNumber": "1.3.5",
        "scName": "Identify Input Purpose",
        "level": "AA",
        "description": "The purpose of each input field collecting information about the user can be programmatically determined when:\n\nThe input field serves a purpose identified in the Input Purposes for User Interface Components section; and\nThe content is implemented using technologies with support for identifying the expected meaning for form input data.",
        "shortDescription": "The purpose of each input field collecting information about the user can be programmatically determined when:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Adaptable",
        "sc": "1.3.6 Identify Purpose",
        "scNumber": "1.3.6",
        "scName": "Identify Purpose",
        "level": "AAA",
        "description": "In content implemented using markup languages, the purpose of User Interface Components, icons, and regions can be programmatically determined.",
        "shortDescription": "In content implemented using markup languages, the purpose of User Interface Components, icons, and regions can be programmatically determined.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.1 Use of Color",
        "scNumber": "1.4.1",
        "scName": "Use of Color",
        "level": "A",
        "description": "Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.\n\nNOTE\nThis success criterion addresses color perception specifically. Other forms of perception are covered in Guideline 1.3 including programmatic access to color and other visual presentation coding.",
        "shortDescription": "Color is not used as the only visual means of conveying information, indicating an action, prompting a response, or distinguishing a visual element.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.2 Audio Control",
        "scNumber": "1.4.2",
        "scName": "Audio Control",
        "level": "A",
        "description": "If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume independently from the overall system volume level.\n\nNOTE\nSince any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether or not it is used to meet other success criteria) must meet this success criterion. See Conformance Requirement 5: Non-Interference.",
        "shortDescription": "If any audio on a Web page plays automatically for more than 3 seconds, either a mechanism is available to pause or stop the audio, or a mechanism is available to control audio volume independently from the overall system volume level.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.3 Contrast (Minimum)",
        "scNumber": "1.4.3",
        "scName": "Contrast (Minimum)",
        "level": "AA",
        "description": "The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following:\n\nLarge Text\nLarge-scale text and images of large-scale text have a contrast ratio of at least 3:1;\n\nIncidental\nText or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.\n\nLogotypes\nText that is part of a logo or brand name has no contrast requirement.",
        "shortDescription": "The visual presentation of text and images of text has a contrast ratio of at least 4.5:1, except for the following:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.4 Resize Text",
        "scNumber": "1.4.4",
        "scName": "Resize Text",
        "level": "AA",
        "description": "Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality.",
        "shortDescription": "Except for captions and images of text, text can be resized without assistive technology up to 200 percent without loss of content or functionality.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.5 Images of Text",
        "scNumber": "1.4.5",
        "scName": "Images of Text",
        "level": "AA",
        "description": "If the technologies being used can achieve the visual presentation, text is used to convey information rather than images of text except for the following:\n\nCustomizable\nThe image of text can be visually customized to the user's requirements;\n\nEssential\nA particular presentation of text is essential to the information being conveyed.\n\nNOTE\nLogotypes (text that is part of a logo or brand name) are considered essential.",
        "shortDescription": "If the technologies being used can achieve the visual presentation, text is used to convey information rather than images of text except for the following:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.6 Contrast (Enhanced)",
        "scNumber": "1.4.6",
        "scName": "Contrast (Enhanced)",
        "level": "AAA",
        "description": "The visual presentation of text and images of text has a contrast ratio of at least 7:1, except for the following:\n\nLarge Text\nLarge-scale text and images of large-scale text have a contrast ratio of at least 4.5:1;\n\nIncidental\nText or images of text that are part of an inactive user interface component, that are pure decoration, that are not visible to anyone, or that are part of a picture that contains significant other visual content, have no contrast requirement.\n\nLogotypes\nText that is part of a logo or brand name has no contrast requirement.",
        "shortDescription": "The visual presentation of text and images of text has a contrast ratio of at least 7:1, except for the following:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.7 Low or No Background Audio",
        "scNumber": "1.4.7",
        "scName": "Low or No Background Audio",
        "level": "AAA",
        "description": "For prerecorded audio-only content that (1) contains primarily speech in the foreground, (2) is not an audio CAPTCHA or audio logo, and (3) is not vocalization intended to be primarily musical expression such as singing or rapping, at least one of the following is true:\n\nNo Background\nThe audio does not contain background sounds.\n\nTurn Off\nThe background sounds can be turned off.\n\n20 dB\nThe background sounds are at least 20 decibels lower than the foreground speech content, with the exception of occasional sounds that last for only one or two seconds.\n\nNOTE\nPer the definition of \"decibel,\" background sound that meets this requirement will be approximately four times quieter than the foreground speech content.",
        "shortDescription": "For prerecorded audio-only content that (1) contains primarily speech in the foreground, (2) is not an audio CAPTCHA or audio logo, and (3) is not vocalization intended to be primarily musical expression such as singing or rapping, at least one of the following is true:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.8 Visual Presentation",
        "scNumber": "1.4.8",
        "scName": "Visual Presentation",
        "level": "AAA",
        "description": "For the visual presentation of blocks of text, a mechanism is available to achieve the following:\n\nForeground and background colors can be selected by the user.\nWidth is no more than 80 characters or glyphs (40 if CJK).\nText is not justified (aligned to both the left and the right margins).\nLine spacing (leading) is at least space-and-a-half within paragraphs, and paragraph spacing is at least 1.5 times larger than the line spacing.\nText can be resized without assistive technology up to 200 percent in a way that does not require the user to scroll horizontally to read a line of text on a full-screen window.",
        "shortDescription": "For the visual presentation of blocks of text, a mechanism is available to achieve the following:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.9 Images of Text (No Exception)",
        "scNumber": "1.4.9",
        "scName": "Images of Text (No Exception)",
        "level": "AAA",
        "description": "Images of text are only used for pure decoration or where a particular presentation of text is essential to the information being conveyed.\n\nNOTE\nLogotypes (text that is part of a logo or brand name) are considered essential.",
        "shortDescription": "Images of text are only used for pure decoration or where a particular presentation of text is essential to the information being conveyed.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.10 Reflow",
        "scNumber": "1.4.10",
        "scName": "Reflow",
        "level": "AA",
        "description": "Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for:\n\nVertical scrolling content at a width equivalent to 320 CSS pixels;\nHorizontal scrolling content at a height equivalent to 256 CSS pixels.\nExcept for parts of the content which require two-dimensional layout for usage or meaning.\n\nNOTE\nNote: 320 CSS pixels is equivalent to a starting viewport width of 1280 CSS pixels wide at 400% zoom. For web content which are designed to scroll horizontally (e.g. with vertical text), the 256 CSS pixels is equivalent to a starting viewport height of 1024px at 400% zoom.\n\nNOTE\nExamples of content which require two-dimensional layout are images, maps, diagrams, video, games, presentations, data tables, and interfaces where it is necessary to keep toolbars in view while manipulating content.",
        "shortDescription": "Content can be presented without loss of information or functionality, and without requiring scrolling in two dimensions for:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.11 Non-text Contrast",
        "scNumber": "1.4.11",
        "scName": "Non-text Contrast",
        "level": "AA",
        "description": "The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s):\n\nUser Interface Components\nVisual information required to identify user interface components and states, except for inactive components or where the appearance of the component is determined by the user agent and not modified by the author;\nGraphical Objects\nParts of graphics required to understand the content, except when a particular presentation of graphics is essential to the information being conveyed.",
        "shortDescription": "The visual presentation of the following have a contrast ratio of at least 3:1 against adjacent color(s):",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.12 Text Spacing",
        "scNumber": "1.4.12",
        "scName": "Text Spacing",
        "level": "AA",
        "description": "In content implemented using markup languages that support the following text style properties, no loss of content or functionality occurs by setting all of the following and by changing no other style property:\n\nLine height (line spacing) to at least 1.5 times the font size;\nSpacing following paragraphs to at least 2 times the font size;\nLetter spacing (tracking) to at least 0.12 times the font size;\nWord spacing to at least 0.16 times the font size.\nException: Human languages and scripts that do not make use of one or more of these text style properties in written text can conform using only the properties that exist for that combination of language and script.",
        "shortDescription": "In content implemented using markup languages that support the following text style properties, no loss of content or functionality occurs by setting all of the following and by changing no other style property:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Perceivable",
        "guideline": "Distinguishable",
        "sc": "1.4.13 Content on Hover or Focus",
        "scNumber": "1.4.13",
        "scName": "Content on Hover or Focus",
        "level": "AA",
        "description": "Where receiving and then removing pointer hover or keyboard focus triggers additional content to become visible and then hidden, the following are true:\n\nDismissable\nA mechanism is available to dismiss the additional content without moving pointer hover or keyboard focus, unless the additional content communicates an input error or does not obscure or replace other content;\nHoverable\nIf pointer hover can trigger the additional content, then the pointer can be moved over the additional content without the additional content disappearing;\nPersistent\nThe additional content remains visible until the hover or focus trigger is removed, the user dismisses it, or its information is no longer valid.\nException: The visual presentation of the additional content is controlled by the user agent and is not modified by the author.\n\nNOTE\nExamples of additional content controlled by the user agent include browser tooltips created through use of the HTML title attribute.\n\nNOTE\nCustom tooltips, sub-menus, and other nonmodal popups that display on hover and focus are examples of additional content covered by this criterion.",
        "shortDescription": "Where receiving and then removing pointer hover or keyboard focus triggers additional content to become visible and then hidden, the following are true:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Keyboard Accessible",
        "sc": "2.1.1 Keyboard",
        "scNumber": "2.1.1",
        "scName": "Keyboard",
        "level": "A",
        "description": "All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes, except where the underlying function requires input that depends on the path of the user's movement and not just the endpoints.\n\nNOTE\nThis exception relates to the underlying function, not the input technique. For example, if using handwriting to enter text, the input technique (handwriting) requires path-dependent input but the underlying function (text input) does not.\n\nNOTE\nThis does not forbid and should not discourage providing mouse input or other input methods in addition to keyboard operation.",
        "shortDescription": "All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes, except where the underlying function requires input that depends on the path of the user's movement and not just the endpoints.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Keyboard Accessible",
        "sc": "2.1.2 No Keyboard Trap",
        "scNumber": "2.1.2",
        "scName": "No Keyboard Trap",
        "level": "A",
        "description": "If keyboard focus can be moved to a component of the page using a keyboard interface, then focus can be moved away from that component using only a keyboard interface, and, if it requires more than unmodified arrow or tab keys or other standard exit methods, the user is advised of the method for moving focus away.\n\nNOTE\nSince any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether it is used to meet other success criteria or not) must meet this success criterion. See Conformance Requirement 5: Non-Interference.",
        "shortDescription": "If keyboard focus can be moved to a component of the page using a keyboard interface, then focus can be moved away from that component using only a keyboard interface, and, if it requires more than unmodified arrow or tab keys or other standard exit methods, the user is advised of the method for moving focus away.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Keyboard Accessible",
        "sc": "2.1.3 Keyboard (No Exception)",
        "scNumber": "2.1.3",
        "scName": "Keyboard (No Exception)",
        "level": "AAA",
        "description": "All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes.",
        "shortDescription": "All functionality of the content is operable through a keyboard interface without requiring specific timings for individual keystrokes.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Keyboard Accessible",
        "sc": "2.1.4 Character Key Shortcuts",
        "scNumber": "2.1.4",
        "scName": "Character Key Shortcuts",
        "level": "A",
        "description": "If a keyboard shortcut is implemented in content using only letter (including upper- and lower-case letters), punctuation, number, or symbol characters, then at least one of the following is true:\n\nTurn off\nA mechanism is available to turn the shortcut off;\nRemap\nA mechanism is available to remap the shortcut to use one or more non-printable keyboard characters (e.g. Ctrl, Alt, etc);\nActive only on focus\nThe keyboard shortcut for a user interface component is only active when that component has focus.",
        "shortDescription": "If a keyboard shortcut is implemented in content using only letter (including upper- and lower-case letters), punctuation, number, or symbol characters, then at least one of the following is true:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Enough Time",
        "sc": "2.2.1 Timing Adjustable",
        "scNumber": "2.2.1",
        "scName": "Timing Adjustable",
        "level": "A",
        "description": "For each time limit that is set by the content, at least one of the following is true:\n\nTurn off\nThe user is allowed to turn off the time limit before encountering it; or\n\nAdjust\nThe user is allowed to adjust the time limit before encountering it over a wide range that is at least ten times the length of the default setting; or\n\nExtend\nThe user is warned before time expires and given at least 20 seconds to extend the time limit with a simple action (for example, \"press the space bar\"), and the user is allowed to extend the time limit at least ten times; or\n\nReal-time Exception\nThe time limit is a required part of a real-time event (for example, an auction), and no alternative to the time limit is possible; or\n\nEssential Exception\nThe time limit is essential and extending it would invalidate the activity; or\n\n20 Hour Exception\nThe time limit is longer than 20 hours.\n\nNOTE\nThis success criterion helps ensure that users can complete tasks without unexpected changes in content or context that are a result of a time limit. This success criterion should be considered in conjunction with Success Criterion 3.2.1, which puts limits on changes of content or context as a result of user action.",
        "shortDescription": "For each time limit that is set by the content, at least one of the following is true:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Enough Time",
        "sc": "2.2.2 Pause, Stop, Hide",
        "scNumber": "2.2.2",
        "scName": "Pause, Stop, Hide",
        "level": "A",
        "description": "For moving, blinking, scrolling, or auto-updating information, all of the following are true:\n\nMoving, blinking, scrolling\nFor any moving, blinking or scrolling information that (1) starts automatically, (2) lasts more than five seconds, and (3) is presented in parallel with other content, there is a mechanism for the user to pause, stop, or hide it unless the movement, blinking, or scrolling is part of an activity where it is essential; and\n\nAuto-updating\nFor any auto-updating information that (1) starts automatically and (2) is presented in parallel with other content, there is a mechanism for the user to pause, stop, or hide it or to control the frequency of the update unless the auto-updating is part of an activity where it is essential.\n\nNOTE\nFor requirements related to flickering or flashing content, refer to Guideline 2.3.\n\nNOTE\nSince any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether it is used to meet other success criteria or not) must meet this success criterion. See Conformance Requirement 5: Non-Interference.\n\nNOTE\nContent that is updated periodically by software or that is streamed to the user agent is not required to preserve or present information that is generated or received between the initiation of the pause and resuming presentation, as this may not be technically possible, and in many situations could be misleading to do so.\n\nNOTE\nAn animation that occurs as part of a preload phase or similar situation can be considered essential if interaction cannot occur during that phase for all users and if not indicating progress could confuse users or cause them to think that content was frozen or broken.",
        "shortDescription": "For moving, blinking, scrolling, or auto-updating information, all of the following are true:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Enough Time",
        "sc": "2.2.3 No Timing",
        "scNumber": "2.2.3",
        "scName": "No Timing",
        "level": "AAA",
        "description": "Timing is not an essential part of the event or activity presented by the content, except for non-interactive synchronized media and real-time events.",
        "shortDescription": "Timing is not an essential part of the event or activity presented by the content, except for non-interactive synchronized media and real-time events.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Enough Time",
        "sc": "2.2.4 Interruptions",
        "scNumber": "2.2.4",
        "scName": "Interruptions",
        "level": "AAA",
        "description": "Interruptions can be postponed or suppressed by the user, except interruptions involving an emergency.",
        "shortDescription": "Interruptions can be postponed or suppressed by the user, except interruptions involving an emergency.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Enough Time",
        "sc": "2.2.5 Re-authenticating",
        "scNumber": "2.2.5",
        "scName": "Re-authenticating",
        "level": "AAA",
        "description": "When an authenticated session expires, the user can continue the activity without loss of data after re-authenticating.",
        "shortDescription": "When an authenticated session expires, the user can continue the activity without loss of data after re-authenticating.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Enough Time",
        "sc": "2.2.6 Timeouts",
        "scNumber": "2.2.6",
        "scName": "Timeouts",
        "level": "AAA",
        "description": "Users are warned of the duration of any user inactivity that could cause data loss, unless the data is preserved for more than 20 hours when the user does not take any actions.\n\nNOTE\nPrivacy regulations may require explicit user consent before user identification has been authenticated and before user data is preserved. In cases where the user is a minor, explicit consent may not be solicited in most jurisdictions, countries or regions. Consultation with privacy professionals and legal counsel is advised when considering data preservation as an approach to satisfy this success criterion.",
        "shortDescription": "Users are warned of the duration of any user inactivity that could cause data loss, unless the data is preserved for more than 20 hours when the user does not take any actions.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Seizures and Physical Reactions",
        "sc": "2.3.1 Flashes or Below Threshold",
        "scNumber": "2.3.1",
        "scName": "Flashes or Below Threshold",
        "level": "A",
        "description": "Web pages do not contain anything that flashes more than three times in any one second period, or the flash is below the general flash and red flash thresholds.\n\nNOTE\nSince any content that does not meet this success criterion can interfere with a user's ability to use the whole page, all content on the Web page (whether it is used to meet other success criteria or not) must meet this success criterion. See Conformance Requirement 5: Non-Interference.",
        "shortDescription": "Web pages do not contain anything that flashes more than three times in any one second period, or the flash is below the general flash and red flash thresholds.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Seizures and Physical Reactions",
        "sc": "2.3.2 Three Flashes",
        "scNumber": "2.3.2",
        "scName": "Three Flashes",
        "level": "AAA",
        "description": "Web pages do not contain anything that flashes more than three times in any one second period.",
        "shortDescription": "Web pages do not contain anything that flashes more than three times in any one second period.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Seizures and Physical Reactions",
        "sc": "2.3.3 Animation from Interactions",
        "scNumber": "2.3.3",
        "scName": "Animation from Interactions",
        "level": "AAA",
        "description": "Motion animation triggered by interaction can be disabled, unless the animation is essential to the functionality or the information being conveyed.",
        "shortDescription": "Motion animation triggered by interaction can be disabled, unless the animation is essential to the functionality or the information being conveyed.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.1 Bypass Blocks",
        "scNumber": "2.4.1",
        "scName": "Bypass Blocks",
        "level": "A",
        "description": "A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.",
        "shortDescription": "A mechanism is available to bypass blocks of content that are repeated on multiple Web pages.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.2 Page Titled",
        "scNumber": "2.4.2",
        "scName": "Page Titled",
        "level": "A",
        "description": "Web pages have titles that describe topic or purpose.",
        "shortDescription": "Web pages have titles that describe topic or purpose.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.3 Focus Order",
        "scNumber": "2.4.3",
        "scName": "Focus Order",
        "level": "A",
        "description": "If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability.",
        "shortDescription": "If a Web page can be navigated sequentially and the navigation sequences affect meaning or operation, focusable components receive focus in an order that preserves meaning and operability.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.4 Link Purpose (In Context)",
        "scNumber": "2.4.4",
        "scName": "Link Purpose (In Context)",
        "level": "A",
        "description": "The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.",
        "shortDescription": "The purpose of each link can be determined from the link text alone or from the link text together with its programmatically determined link context, except where the purpose of the link would be ambiguous to users in general.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.5 Multiple Ways",
        "scNumber": "2.4.5",
        "scName": "Multiple Ways",
        "level": "AA",
        "description": "More than one way is available to locate a Web page within a set of Web pages except where the Web Page is the result of, or a step in, a process.",
        "shortDescription": "More than one way is available to locate a Web page within a set of Web pages except where the Web Page is the result of, or a step in, a process.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.6 Headings and Labels",
        "scNumber": "2.4.6",
        "scName": "Headings and Labels",
        "level": "AA",
        "description": "Headings and labels describe topic or purpose.",
        "shortDescription": "Headings and labels describe topic or purpose.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.7 Focus Visible",
        "scNumber": "2.4.7",
        "scName": "Focus Visible",
        "level": "AA",
        "description": "Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.",
        "shortDescription": "Any keyboard operable user interface has a mode of operation where the keyboard focus indicator is visible.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.8 Location",
        "scNumber": "2.4.8",
        "scName": "Location",
        "level": "AAA",
        "description": "Information about the user's location within a set of Web pages is available.",
        "shortDescription": "Information about the user's location within a set of Web pages is available.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.9 (Link Purpose (Link Only)",
        "scNumber": "2.4.9",
        "scName": "(Link Purpose (Link Only)",
        "level": "AAA",
        "description": "A mechanism is available to allow the purpose of each link to be identified from link text alone, except where the purpose of the link would be ambiguous to users in general.",
        "shortDescription": "A mechanism is available to allow the purpose of each link to be identified from link text alone, except where the purpose of the link would be ambiguous to users in general.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Navigable",
        "sc": "2.4.10 Section Headings",
        "scNumber": "2.4.10",
        "scName": "Section Headings",
        "level": "AAA",
        "description": "Section headings are used to organize the content.\n\nNOTE\n\"Heading\" is used in its general sense and includes titles and other ways to add a heading to different types of content.\n\nNOTE\nThis success criterion covers sections within writing, not user interface components. User Interface components are covered under Success Criterion 4.1.2.",
        "shortDescription": "Section headings are used to organize the content.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Operable",
        "guideline": "Input Modalities",
        "sc": "2.5.1 Pointer Gestures",
        "scNumber": "2.5.1",
        "scName": "Pointer Gestures",
        "level": "A",
        "description": "All functionality that uses multipoint or path-based gestures for operation can be operated with a single pointer without a path-based gesture, unless a multipoint or path-based gesture is essential.\n\nNOTE\nThis requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).",
        "shortDescription": "All functionality that uses multipoint or path-based gestures for operation can be operated with a single pointer without a path-based gesture, unless a multipoint or path-based gesture is essential.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Input Modalities",
        "sc": "2.5.2 Pointer Cancellation",
        "scNumber": "2.5.2",
        "scName": "Pointer Cancellation",
        "level": "A",
        "description": "For functionality that can be operated using a single pointer, at least one of the following is true:\n\nNo Down-Event\nThe down-event of the pointer is not used to execute any part of the function;\nAbort or Undo\nCompletion of the function is on the up-event, and a mechanism is available to abort the function before completion or to undo the function after completion;\nUp Reversal\nThe up-event reverses any outcome of the preceding down-event;\nEssential\nCompleting the function on the down-event is essential.\nNOTE\nFunctions that emulate a keyboard or numeric keypad key press are considered essential.\n\nNOTE\nThis requirement applies to web content that interprets pointer actions (i.e. this does not apply to actions that are required to operate the user agent or assistive technology).",
        "shortDescription": "For functionality that can be operated using a single pointer, at least one of the following is true:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Input Modalities",
        "sc": "2.5.3 Label in Name",
        "scNumber": "2.5.3",
        "scName": "Label in Name",
        "level": "A",
        "description": "For user interface components with labels that include text or images of text, the name contains the text that is presented visually.\n\nNOTE\nA best practice is to have the text of the label at the start of the name.",
        "shortDescription": "For user interface components with labels that include text or images of text, the name contains the text that is presented visually.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Input Modalities",
        "sc": "2.5.4 Motion Actuation",
        "scNumber": "2.5.4",
        "scName": "Motion Actuation",
        "level": "A",
        "description": "Functionality that can be operated by device motion or user motion can also be operated by user interface components and responding to the motion can be disabled to prevent accidental actuation, except when:\n\nSupported Interface\nThe motion is used to operate functionality through an accessibility supported interface;\nEssential\nThe motion is essential for the function and doing so would invalidate the activity.",
        "shortDescription": "Functionality that can be operated by device motion or user motion can also be operated by user interface components and responding to the motion can be disabled to prevent accidental actuation, except when:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Input Modalities",
        "sc": "2.5.5 Target Size",
        "scNumber": "2.5.5",
        "scName": "Target Size",
        "level": "AAA",
        "description": "The size of the target for pointer inputs is at least 44 by 44 CSS pixels except when:\n\nEquivalent\nThe target is available through an equivalent link or control on the same page that is at least 44 by 44 CSS pixels;\nInline\nThe target is in a sentence or block of text;\nUser Agent Control\nThe size of the target is determined by the user agent and is not modified by the author;\nEssential\nA particular presentation of the target is essential to the information being conveyed.",
        "shortDescription": "The size of the target for pointer inputs is at least 44 by 44 CSS pixels except when:",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Operable",
        "guideline": "Input Modalities",
        "sc": "2.5.6 Concurrent Input Mechanisms",
        "scNumber": "2.5.6",
        "scName": "Concurrent Input Mechanisms",
        "level": "AAA",
        "description": "Web content does not restrict use of input modalities available on a platform except where the restriction is essential, required to ensure the security of the content, or required to respect user settings.",
        "shortDescription": "Web content does not restrict use of input modalities available on a platform except where the restriction is essential, required to ensure the security of the content, or required to respect user settings.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Readable",
        "sc": "3.1.1 Language of Page",
        "scNumber": "3.1.1",
        "scName": "Language of Page",
        "level": "A",
        "description": "The default human language of each Web page can be programmatically determined.",
        "shortDescription": "The default human language of each Web page can be programmatically determined.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Readable",
        "sc": "3.1.2 Language of Parts",
        "scNumber": "3.1.2",
        "scName": "Language of Parts",
        "level": "AA",
        "description": "The human language of each passage or phrase in the content can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text.",
        "shortDescription": "The human language of each passage or phrase in the content can be programmatically determined except for proper names, technical terms, words of indeterminate language, and words or phrases that have become part of the vernacular of the immediately surrounding text.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Readable",
        "sc": "3.1.3 Unusual Words",
        "scNumber": "3.1.3",
        "scName": "Unusual Words",
        "level": "AAA",
        "description": "A mechanism is available for identifying specific definitions of words or phrases used in an unusual or restricted way, including idioms and jargon.",
        "shortDescription": "A mechanism is available for identifying specific definitions of words or phrases used in an unusual or restricted way, including idioms and jargon.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Readable",
        "sc": "3.1.4 Abbreviations",
        "scNumber": "3.1.4",
        "scName": "Abbreviations",
        "level": "AAA",
        "description": "A mechanism for identifying the expanded form or meaning of abbreviations is available.",
        "shortDescription": "A mechanism for identifying the expanded form or meaning of abbreviations is available.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Readable",
        "sc": "3.1.5 Reading Level",
        "scNumber": "3.1.5",
        "scName": "Reading Level",
        "level": "AAA",
        "description": "When text requires reading ability more advanced than the lower secondary education level after removal of proper names and titles, supplemental content, or a version that does not require reading ability more advanced than the lower secondary education level, is available.",
        "shortDescription": "When text requires reading ability more advanced than the lower secondary education level after removal of proper names and titles, supplemental content, or a version that does not require reading ability more advanced than the lower secondary education level, is available.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Readable",
        "sc": "3.1.6 Pronunciation",
        "scNumber": "3.1.6",
        "scName": "Pronunciation",
        "level": "AAA",
        "description": "A mechanism is available for identifying specific pronunciation of words where meaning of the words, in context, is ambiguous without knowing the pronunciation.",
        "shortDescription": "A mechanism is available for identifying specific pronunciation of words where meaning of the words, in context, is ambiguous without knowing the pronunciation.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Predictable",
        "sc": "3.2.1 On Focus",
        "scNumber": "3.2.1",
        "scName": "On Focus",
        "level": "A",
        "description": "When any user interface component receives focus, it does not initiate a change of context.",
        "shortDescription": "When any user interface component receives focus, it does not initiate a change of context.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Predictable",
        "sc": "3.2.2 On Input",
        "scNumber": "3.2.2",
        "scName": "On Input",
        "level": "A",
        "description": "Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised of the behavior before using the component.",
        "shortDescription": "Changing the setting of any user interface component does not automatically cause a change of context unless the user has been advised of the behavior before using the component.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Predictable",
        "sc": "3.2.3 Consistent Navigation",
        "scNumber": "3.2.3",
        "scName": "Consistent Navigation",
        "level": "AA",
        "description": "Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in the same relative order each time they are repeated, unless a change is initiated by the user.",
        "shortDescription": "Navigational mechanisms that are repeated on multiple Web pages within a set of Web pages occur in the same relative order each time they are repeated, unless a change is initiated by the user.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Predictable",
        "sc": "3.2.4 Consistent Identification",
        "scNumber": "3.2.4",
        "scName": "Consistent Identification",
        "level": "AA",
        "description": "Components that have the same functionality within a set of Web pages are identified consistently.",
        "shortDescription": "Components that have the same functionality within a set of Web pages are identified consistently.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Predictable",
        "sc": "3.2.5 Change on Request",
        "scNumber": "3.2.5",
        "scName": "Change on Request",
        "level": "AAA",
        "description": "Changes of context are initiated only by user request or a mechanism is available to turn off such changes.",
        "shortDescription": "Changes of context are initiated only by user request or a mechanism is available to turn off such changes.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Input Assistance",
        "sc": "3.3.1 Error Identification",
        "scNumber": "3.3.1",
        "scName": "Error Identification",
        "level": "A",
        "description": "If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text.",
        "shortDescription": "If an input error is automatically detected, the item that is in error is identified and the error is described to the user in text.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Input Assistance",
        "sc": "3.3.2 Labels or Instructions",
        "scNumber": "3.3.2",
        "scName": "Labels or Instructions",
        "level": "A",
        "description": "Labels or instructions are provided when content requires user input.",
        "shortDescription": "Labels or instructions are provided when content requires user input.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Understandable",
        "guideline": "Input Assistance",
        "sc": "3.3.3 Error Suggestion",
        "scNumber": "3.3.3",
        "scName": "Error Suggestion",
        "level": "AA",
        "description": "If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user, unless it would jeopardize the security or purpose of the content.",
        "shortDescription": "If an input error is automatically detected and suggestions for correction are known, then the suggestions are provided to the user, unless it would jeopardize the security or purpose of the content.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Input Assistance",
        "sc": "3.3.4 Error Prevention (Legal, Financial, Data)",
        "scNumber": "3.3.4",
        "scName": "Error Prevention (Legal, Financial, Data)",
        "level": "AA",
        "description": "For Web pages that cause legal commitments or financial transactions for the user to occur, that modify or delete user-controllable data in data storage systems, or that submit user test responses, at least one of the following is true:\n\nReversible\nSubmissions are reversible.\nChecked\nData entered by the user is checked for input errors and the user is provided an opportunity to correct them.\nConfirmed\nA mechanism is available for reviewing, confirming, and correcting information before finalizing the submission.",
        "shortDescription": "For Web pages that cause legal commitments or financial transactions for the user to occur, that modify or delete user-controllable data in data storage systems, or that submit user test responses, at least one of the following is true:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Input Assistance",
        "sc": "3.3.5 Help",
        "scNumber": "3.3.5",
        "scName": "Help",
        "level": "AAA",
        "description": "Context-sensitive help is available.",
        "shortDescription": "Context-sensitive help is available.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Understandable",
        "guideline": "Input Assistance",
        "sc": "3.3.6 Error Prevention (All)",
        "scNumber": "3.3.6",
        "scName": "Error Prevention (All)",
        "level": "AAA",
        "description": "For Web pages that require the user to submit information, at least one of the following is true:\n\nReversible\nSubmissions are reversible.\nChecked\nData entered by the user is checked for input errors and the user is provided an opportunity to correct them.\nConfirmed\nA mechanism is available for reviewing, confirming, and correcting information before finalizing the submission.",
        "shortDescription": "For Web pages that require the user to submit information, at least one of the following is true:",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Robust",
        "guideline": "Compatible",
        "sc": "4.1.1 Parsing",
        "scNumber": "4.1.1",
        "scName": "Parsing",
        "level": "A",
        "description": "In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features.\n\nNOTE\nStart and end tags that are missing a critical character in their formation, such as a closing angle bracket or a mismatched attribute value quotation mark are not complete.",
        "shortDescription": "In content implemented using markup languages, elements have complete start and end tags, elements are nested according to their specifications, elements do not contain duplicate attributes, and any IDs are unique, except where the specifications allow these features.",
        "screenReaderDetectable": "No"
    },
    {
        "principle": "Robust",
        "guideline": "Compatible",
        "sc": "4.1.2 Name, Role, Value",
        "scNumber": "4.1.2",
        "scName": "Name, Role, Value",
        "level": "A",
        "description": "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.\n\nNOTE\nThis success criterion is primarily for Web authors who develop or script their own user interface components. For example, standard HTML controls already meet this success criterion when used according to specification.",
        "shortDescription": "For all user interface components (including but not limited to: form elements, links and components generated by scripts), the name and role can be programmatically determined; states, properties, and values that can be set by the user can be programmatically set; and notification of changes to these items is available to user agents, including assistive technologies.",
        "screenReaderDetectable": "Yes"
    },
    {
        "principle": "Robust",
        "guideline": "Compatible",
        "sc": "4.1.3 Status Messages",
        "scNumber": "4.1.3",
        "scName": "Status Messages",
        "level": "AA",
        "description": "In content implemented using markup languages, status messages can be programmatically determined through role or properties such that they can be presented to the user by assistive technologies without receiving focus.",
        "shortDescription": "In content implemented using markup languages, status messages can be programmatically determined through role or properties such that they can be presented to the user by assistive technologies without receiving focus.",
        "screenReaderDetectable": "Yes"
    }
];
